version: "3"
services:
  app:
    build:
      context: ./php/docker
      args:
        - TZ=${TZ}
    volumes:
      - ./php/src:/app
      - ./php/logs:/var/log/php
      - ./php/docker/php.ini:/usr/local/etc/php/php.ini
    working_dir: /app
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
      - TZ=${TZ}
  db:
    image: mysql:8.0
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/logs:/var/log/mysql
      - ./db/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${TZ}
  web:
    image: nginx:1.19-alpine
    depends_on:
      - app
    ports:
      - 8080:80
    volumes:
      - ./php/src:/app
      - ./nginx/logs:/var/log/nginx
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - TZ=${TZ}
